

class Message:
    login = "LoggedIn successfully"
    enter_email = "Please enter email"
    enter_password = "Please enter password"
    register_mail = "Please enter registered email"
    invalid_password = "Incorrect password"
    login_block = "You are blocked by admin"
    login_success = "Loggedin successfully"
    mandatory_keys = "Please choose mandatory fields"
    data_missing = "Some datas not found"
    phonenumber_exist = "Phone number already exist"
    email_exist = "Email already exist"
    password_mismatched = "Password are missmatched"
    registerd_success = "Registered successfully"
    signup = "Signedup successfully"
    logout_success = "Logout successfully"
    unit_listed = "Unit listed successfully"
    property_created = "Property created successfully"
    property_exist = "Property already exists with this ULPIN number"
    check_property = "Please check property details"
    property_unit_exist = "Please check the property units"
    property_listed_successfuly = "Property listed successfully"
    tenant_created = "Tenant created successfully"
    tenant_property_exist = "Tenant is already mapped with this property"
    property_exist_another_tenant = "Property already exist for another tenant"
    tenant_property_mapped = "Tenant and properties are mapped"
    tenanat_not_found = "Tenant not found"
    property_not_found = "Property not found"
    tenanat_listed = "Tenant listed successfully"
    tenant_viewed = "Tenant viewed successfully"
    
    
    #exceptions
    server_error = "Internal server error"